[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"
cache_path = "cache"

# See more config options https://github.com/foundry-rs/foundry/tree/master/config

[profile.default.optimizer]
enabled = true
runs = 200

[profile.default.model_checker]
engine = "chc"
timeout = 10000
targets = ["assert"]

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = true
int_types = "long"

[rpc_endpoints]
# Polkadot Asset Hub RPC endpoint
asset_hub = "${ASSET_HUB_RPC}"
# Local development node
localhost = "http://127.0.0.1:8545"